/**
 * @externs
 * @suppress {duplicate}
 */
// NOTE: generated by tsickle, do not edit.
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/bicycling-layer.ts:

/** @record @struct */
function BicyclingLayerOutput() {}

/** @record @struct */
function BicyclingLayerInput() {}
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/components/ngui-map.component.ts:

/** @record @struct */
function NguiMapComponentOutput() {}
 /** @type {?} */
NguiMapComponentOutput.prototype.bounds_changed;
 /** @type {?} */
NguiMapComponentOutput.prototype.center_changed;
 /** @type {?} */
NguiMapComponentOutput.prototype.click;
 /** @type {?} */
NguiMapComponentOutput.prototype.dblclick;
 /** @type {?} */
NguiMapComponentOutput.prototype.drag;
 /** @type {?} */
NguiMapComponentOutput.prototype.dragend;
 /** @type {?} */
NguiMapComponentOutput.prototype.dragstart;
 /** @type {?} */
NguiMapComponentOutput.prototype.heading_changed;
 /** @type {?} */
NguiMapComponentOutput.prototype.idle;
 /** @type {?} */
NguiMapComponentOutput.prototype.typeid_changed;
 /** @type {?} */
NguiMapComponentOutput.prototype.mousemove;
 /** @type {?} */
NguiMapComponentOutput.prototype.mouseout;
 /** @type {?} */
NguiMapComponentOutput.prototype.mouseover;
 /** @type {?} */
NguiMapComponentOutput.prototype.projection_changed;
 /** @type {?} */
NguiMapComponentOutput.prototype.resize;
 /** @type {?} */
NguiMapComponentOutput.prototype.rightclick;
 /** @type {?} */
NguiMapComponentOutput.prototype.tilesloaded;
 /** @type {?} */
NguiMapComponentOutput.prototype.tile_changed;
 /** @type {?} */
NguiMapComponentOutput.prototype.zoom_changed;
 /** @type {?} */
NguiMapComponentOutput.prototype.mapClick;
 /** @type {?} */
NguiMapComponentOutput.prototype.mapMouseover;
 /** @type {?} */
NguiMapComponentOutput.prototype.mapMouseout;
 /** @type {?} */
NguiMapComponentOutput.prototype.mapMousemove;
 /** @type {?} */
NguiMapComponentOutput.prototype.mapDrag;
 /** @type {?} */
NguiMapComponentOutput.prototype.mapDragend;
 /** @type {?} */
NguiMapComponentOutput.prototype.mapDragstart;

/** @record @struct */
function NguiMapComponentInput() {}
 /** @type {?} */
NguiMapComponentInput.prototype.backgroundColor;
 /** @type {?} */
NguiMapComponentInput.prototype.center;
 /** @type {?} */
NguiMapComponentInput.prototype.disableDefaultUI;
 /** @type {?} */
NguiMapComponentInput.prototype.disableDoubleClickZoom;
 /** @type {?} */
NguiMapComponentInput.prototype.draggable;
 /** @type {?} */
NguiMapComponentInput.prototype.draggableCursor;
 /** @type {?} */
NguiMapComponentInput.prototype.draggingCursor;
 /** @type {?} */
NguiMapComponentInput.prototype.heading;
 /** @type {?} */
NguiMapComponentInput.prototype.keyboardShortcuts;
 /** @type {?} */
NguiMapComponentInput.prototype.mapMaker;
 /** @type {?} */
NguiMapComponentInput.prototype.mapTypeControl;
 /** @type {?} */
NguiMapComponentInput.prototype.mapTypeId;
 /** @type {?} */
NguiMapComponentInput.prototype.maxZoom;
 /** @type {?} */
NguiMapComponentInput.prototype.minZoom;
 /** @type {?} */
NguiMapComponentInput.prototype.noClear;
 /** @type {?} */
NguiMapComponentInput.prototype.overviewMapControl;
 /** @type {?} */
NguiMapComponentInput.prototype.panControl;
 /** @type {?} */
NguiMapComponentInput.prototype.panControlOptions;
 /** @type {?} */
NguiMapComponentInput.prototype.rotateControl;
 /** @type {?} */
NguiMapComponentInput.prototype.scaleControl;
 /** @type {?} */
NguiMapComponentInput.prototype.scrollwheel;
 /** @type {?} */
NguiMapComponentInput.prototype.streetView;
 /** @type {?} */
NguiMapComponentInput.prototype.styles;
 /** @type {?} */
NguiMapComponentInput.prototype.tilt;
 /** @type {?} */
NguiMapComponentInput.prototype.zoom;
 /** @type {?} */
NguiMapComponentInput.prototype.streetViewControl;
 /** @type {?} */
NguiMapComponentInput.prototype.zoomControl;
 /** @type {?} */
NguiMapComponentInput.prototype.zoomControlOptions;
 /** @type {?} */
NguiMapComponentInput.prototype.mapTypeControlOptions;
 /** @type {?} */
NguiMapComponentInput.prototype.overviewMapControlOptions;
 /** @type {?} */
NguiMapComponentInput.prototype.rotateControlOptions;
 /** @type {?} */
NguiMapComponentInput.prototype.scaleControlOptions;
 /** @type {?} */
NguiMapComponentInput.prototype.streetViewControlOptions;
 /** @type {?} */
NguiMapComponentInput.prototype.fullscreenControl;
 /** @type {?} */
NguiMapComponentInput.prototype.fullscreenControlOptions;
 /** @type {?} */
NguiMapComponentInput.prototype.options;
 /** @type {?} */
NguiMapComponentInput.prototype.geoFallbackCenter;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/components/info-window.ts:

/** @record @struct */
function InfoWindowOutput() {}
 /** @type {?} */
InfoWindowOutput.prototype.closeclick;
 /** @type {?} */
InfoWindowOutput.prototype.content_changed;
 /** @type {?} */
InfoWindowOutput.prototype.domready;
 /** @type {?} */
InfoWindowOutput.prototype.position_changed;
 /** @type {?} */
InfoWindowOutput.prototype.zindex_changed;

/** @record @struct */
function InfoWindowInput() {}
 /** @type {?} */
InfoWindowInput.prototype.content;
 /** @type {?} */
InfoWindowInput.prototype.disableAutoPan;
 /** @type {?} */
InfoWindowInput.prototype.maxWidth;
 /** @type {?} */
InfoWindowInput.prototype.pixelOffset;
 /** @type {?} */
InfoWindowInput.prototype.position;
 /** @type {?} */
InfoWindowInput.prototype.zIndex;
 /** @type {?} */
InfoWindowInput.prototype.options;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/components/custom-marker.ts:

/** @record @struct */
function CustomMarkerOutput() {}
 /** @type {?} */
CustomMarkerOutput.prototype.animationChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.click;
 /** @type {?} */
CustomMarkerOutput.prototype.clickableChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.cursorChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.dblclick;
 /** @type {?} */
CustomMarkerOutput.prototype.drag;
 /** @type {?} */
CustomMarkerOutput.prototype.dragend;
 /** @type {?} */
CustomMarkerOutput.prototype.draggableChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.dragstart;
 /** @type {?} */
CustomMarkerOutput.prototype.flatChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.iconChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.mousedown;
 /** @type {?} */
CustomMarkerOutput.prototype.mouseout;
 /** @type {?} */
CustomMarkerOutput.prototype.mouseover;
 /** @type {?} */
CustomMarkerOutput.prototype.mouseup;
 /** @type {?} */
CustomMarkerOutput.prototype.positionChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.rightclick;
 /** @type {?} */
CustomMarkerOutput.prototype.shapeChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.titleChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.visibleChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.zindexChanged;
 /** @type {?} */
CustomMarkerOutput.prototype.map_click;
 /** @type {?} */
CustomMarkerOutput.prototype.map_mouseover;
 /** @type {?} */
CustomMarkerOutput.prototype.map_mouseout;
 /** @type {?} */
CustomMarkerOutput.prototype.map_mouseup;
 /** @type {?} */
CustomMarkerOutput.prototype.map_mousedown;
 /** @type {?} */
CustomMarkerOutput.prototype.map_drag;
 /** @type {?} */
CustomMarkerOutput.prototype.map_dragend;

/** @record @struct */
function CustomMarkerInput() {}
 /** @type {?} */
CustomMarkerInput.prototype.position;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/circle.ts:

/** @record @struct */
function CircleOutput() {}
 /** @type {?} */
CircleOutput.prototype.centerChanged;
 /** @type {?} */
CircleOutput.prototype.click;
 /** @type {?} */
CircleOutput.prototype.dblclick;
 /** @type {?} */
CircleOutput.prototype.drag;
 /** @type {?} */
CircleOutput.prototype.dragend;
 /** @type {?} */
CircleOutput.prototype.dragstart;
 /** @type {?} */
CircleOutput.prototype.mousedown;
 /** @type {?} */
CircleOutput.prototype.mousemove;
 /** @type {?} */
CircleOutput.prototype.mouseout;
 /** @type {?} */
CircleOutput.prototype.mouseover;
 /** @type {?} */
CircleOutput.prototype.mouseup;
 /** @type {?} */
CircleOutput.prototype.radiusChanged;
 /** @type {?} */
CircleOutput.prototype.rightclick;

/** @record @struct */
function CircleInput() {}
 /** @type {?} */
CircleInput.prototype.center;
 /** @type {?} */
CircleInput.prototype.clickable;
 /** @type {?} */
CircleInput.prototype.draggable;
 /** @type {?} */
CircleInput.prototype.editable;
 /** @type {?} */
CircleInput.prototype.fillColor;
 /** @type {?} */
CircleInput.prototype.fillOpacity;
 /** @type {?} */
CircleInput.prototype.map;
 /** @type {?} */
CircleInput.prototype.radius;
 /** @type {?} */
CircleInput.prototype.strokeColor;
 /** @type {?} */
CircleInput.prototype.strokeOpacity;
 /** @type {?} */
CircleInput.prototype.strokePosition;
 /** @type {?} */
CircleInput.prototype.strokeWeight;
 /** @type {?} */
CircleInput.prototype.visible;
 /** @type {?} */
CircleInput.prototype.zIndex;
 /** @type {?} */
CircleInput.prototype.options;
 /** @type {?} */
CircleInput.prototype.geoFallbackCenter;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/data-layer.ts:

/** @record @struct */
function DataLayerOutput() {}
 /** @type {?} */
DataLayerOutput.prototype.addfeature;
 /** @type {?} */
DataLayerOutput.prototype.click;
 /** @type {?} */
DataLayerOutput.prototype.dblclick;
 /** @type {?} */
DataLayerOutput.prototype.mousedown;
 /** @type {?} */
DataLayerOutput.prototype.mouseout;
 /** @type {?} */
DataLayerOutput.prototype.mouseover;
 /** @type {?} */
DataLayerOutput.prototype.mouseup;
 /** @type {?} */
DataLayerOutput.prototype.removefeature;
 /** @type {?} */
DataLayerOutput.prototype.removeproperty;
 /** @type {?} */
DataLayerOutput.prototype.rightclick;
 /** @type {?} */
DataLayerOutput.prototype.setgeometry;
 /** @type {?} */
DataLayerOutput.prototype.setproperty;

/** @record @struct */
function DataLayerInput() {}
 /** @type {?} */
DataLayerInput.prototype.controlPosition;
 /** @type {?} */
DataLayerInput.prototype.controls;
 /** @type {?} */
DataLayerInput.prototype.drawingMode;
 /** @type {?} */
DataLayerInput.prototype.featureFactory;
 /** @type {?} */
DataLayerInput.prototype.style;
 /** @type {?} */
DataLayerInput.prototype.geoJson;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/directions-renderer.ts:

/** @record @struct */
function DirectionsRendererOutput() {}
 /** @type {?} */
DirectionsRendererOutput.prototype.directions_changed;

/** @record @struct */
function DirectionsRendererInput() {}
 /** @type {?} */
DirectionsRendererInput.prototype.directions;
 /** @type {?} */
DirectionsRendererInput.prototype.draggable;
 /** @type {?} */
DirectionsRendererInput.prototype.hideRouteList;
 /** @type {?} */
DirectionsRendererInput.prototype.infoWindow;
 /** @type {?} */
DirectionsRendererInput.prototype.panel;
 /** @type {?} */
DirectionsRendererInput.prototype.markerOptions;
 /** @type {?} */
DirectionsRendererInput.prototype.polylineOptions;
 /** @type {?} */
DirectionsRendererInput.prototype.preserveViewport;
 /** @type {?} */
DirectionsRendererInput.prototype.routeIndex;
 /** @type {?} */
DirectionsRendererInput.prototype.suppressBicyclingLayer;
 /** @type {?} */
DirectionsRendererInput.prototype.suppressInfoWindows;
 /** @type {?} */
DirectionsRendererInput.prototype.suppressMarkers;
 /** @type {?} */
DirectionsRendererInput.prototype.suppressPolylines;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/drawing-manager.ts:

/** @record @struct */
function DrawingManagerOutput() {}
 /** @type {?} */
DrawingManagerOutput.prototype.circlecomplete;
 /** @type {?} */
DrawingManagerOutput.prototype.markercomplete;
 /** @type {?} */
DrawingManagerOutput.prototype.overlaycomplete;
 /** @type {?} */
DrawingManagerOutput.prototype.polygoncomplete;
 /** @type {?} */
DrawingManagerOutput.prototype.polylinecomplete;
 /** @type {?} */
DrawingManagerOutput.prototype.rectanglecomplete;

/** @record @struct */
function DrawingManagerInput() {}
 /** @type {?} */
DrawingManagerInput.prototype.options;
 /** @type {?} */
DrawingManagerInput.prototype.circleOptions;
 /** @type {?} */
DrawingManagerInput.prototype.drawingControl;
 /** @type {?} */
DrawingManagerInput.prototype.drawingControlOptions;
 /** @type {?} */
DrawingManagerInput.prototype.drawingMode;
 /** @type {?} */
DrawingManagerInput.prototype.map;
 /** @type {?} */
DrawingManagerInput.prototype.markerOptions;
 /** @type {?} */
DrawingManagerInput.prototype.polygonOptions;
 /** @type {?} */
DrawingManagerInput.prototype.polylineOptions;
 /** @type {?} */
DrawingManagerInput.prototype.rectangleOptions;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/ground-overlay.ts:

/** @record @struct */
function GroundOverlayOutput() {}
 /** @type {?} */
GroundOverlayOutput.prototype.click;
 /** @type {?} */
GroundOverlayOutput.prototype.dblclick;

/** @record @struct */
function GroundOverlayInput() {}
 /** @type {?} */
GroundOverlayInput.prototype.url;
 /** @type {?} */
GroundOverlayInput.prototype.bounds;
 /** @type {?} */
GroundOverlayInput.prototype.clickable;
 /** @type {?} */
GroundOverlayInput.prototype.opacity;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/heatmap-layer.ts:

/** @record @struct */
function HeatmapLayerOutput() {}

/** @record @struct */
function HeatmapLayerInput() {}
 /** @type {?} */
HeatmapLayerInput.prototype.data;
 /** @type {?} */
HeatmapLayerInput.prototype.dissipating;
 /** @type {?} */
HeatmapLayerInput.prototype.gradient;
 /** @type {?} */
HeatmapLayerInput.prototype.maxIntensity;
 /** @type {?} */
HeatmapLayerInput.prototype.opacity;
 /** @type {?} */
HeatmapLayerInput.prototype.radius;
 /** @type {?} */
HeatmapLayerInput.prototype.options;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/kml-layer.ts:

/** @record @struct */
function KmlLayerOutput() {}
 /** @type {?} */
KmlLayerOutput.prototype.click;
 /** @type {?} */
KmlLayerOutput.prototype.defaultviewport_changed;
 /** @type {?} */
KmlLayerOutput.prototype.status_changed;

/** @record @struct */
function KmlLayerInput() {}
 /** @type {?} */
KmlLayerInput.prototype.clickable;
 /** @type {?} */
KmlLayerInput.prototype.preserveViewport;
 /** @type {?} */
KmlLayerInput.prototype.screenOverlays;
 /** @type {?} */
KmlLayerInput.prototype.suppressInfoWindows;
 /** @type {?} */
KmlLayerInput.prototype.url;
 /** @type {?} */
KmlLayerInput.prototype.zIndex;
 /** @type {?} */
KmlLayerInput.prototype.options;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/marker.ts:

/** @record @struct */
function MarkerOutput() {}
 /** @type {?} */
MarkerOutput.prototype.animationChanged;
 /** @type {?} */
MarkerOutput.prototype.click;
 /** @type {?} */
MarkerOutput.prototype.clickableChanged;
 /** @type {?} */
MarkerOutput.prototype.cursorChanged;
 /** @type {?} */
MarkerOutput.prototype.dblclick;
 /** @type {?} */
MarkerOutput.prototype.drag;
 /** @type {?} */
MarkerOutput.prototype.dragend;
 /** @type {?} */
MarkerOutput.prototype.draggableChanged;
 /** @type {?} */
MarkerOutput.prototype.dragstart;
 /** @type {?} */
MarkerOutput.prototype.flatChanged;
 /** @type {?} */
MarkerOutput.prototype.iconChanged;
 /** @type {?} */
MarkerOutput.prototype.mousedown;
 /** @type {?} */
MarkerOutput.prototype.mouseout;
 /** @type {?} */
MarkerOutput.prototype.mouseover;
 /** @type {?} */
MarkerOutput.prototype.mouseup;
 /** @type {?} */
MarkerOutput.prototype.positionChanged;
 /** @type {?} */
MarkerOutput.prototype.rightclick;
 /** @type {?} */
MarkerOutput.prototype.shapeChanged;
 /** @type {?} */
MarkerOutput.prototype.titleChanged;
 /** @type {?} */
MarkerOutput.prototype.visibleChanged;
 /** @type {?} */
MarkerOutput.prototype.zindexChanged;

/** @record @struct */
function MarkerInput() {}
 /** @type {?} */
MarkerInput.prototype.anchorPoint;
 /** @type {?} */
MarkerInput.prototype.animation;
 /** @type {?} */
MarkerInput.prototype.clickable;
 /** @type {?} */
MarkerInput.prototype.cursor;
 /** @type {?} */
MarkerInput.prototype.draggable;
 /** @type {?} */
MarkerInput.prototype.icon;
 /** @type {?} */
MarkerInput.prototype.label;
 /** @type {?} */
MarkerInput.prototype.opacity;
 /** @type {?} */
MarkerInput.prototype.optimized;
 /** @type {?} */
MarkerInput.prototype.place;
 /** @type {?} */
MarkerInput.prototype.position;
 /** @type {?} */
MarkerInput.prototype.shape;
 /** @type {?} */
MarkerInput.prototype.title;
 /** @type {?} */
MarkerInput.prototype.visible;
 /** @type {?} */
MarkerInput.prototype.zIndex;
 /** @type {?} */
MarkerInput.prototype.options;
 /** @type {?} */
MarkerInput.prototype.geoFallbackPosition;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/polygon.ts:

/** @record @struct */
function PolygonOutput() {}
 /** @type {?} */
PolygonOutput.prototype.click;
 /** @type {?} */
PolygonOutput.prototype.dblclick;
 /** @type {?} */
PolygonOutput.prototype.drag;
 /** @type {?} */
PolygonOutput.prototype.dragend;
 /** @type {?} */
PolygonOutput.prototype.dragstart;
 /** @type {?} */
PolygonOutput.prototype.mousedown;
 /** @type {?} */
PolygonOutput.prototype.mousemove;
 /** @type {?} */
PolygonOutput.prototype.mouseout;
 /** @type {?} */
PolygonOutput.prototype.mouseover;
 /** @type {?} */
PolygonOutput.prototype.mouseup;
 /** @type {?} */
PolygonOutput.prototype.rightclick;

/** @record @struct */
function PolygonInput() {}
 /** @type {?} */
PolygonInput.prototype.clickable;
 /** @type {?} */
PolygonInput.prototype.draggable;
 /** @type {?} */
PolygonInput.prototype.editable;
 /** @type {?} */
PolygonInput.prototype.fillColor;
 /** @type {?} */
PolygonInput.prototype.fillOpacity;
 /** @type {?} */
PolygonInput.prototype.geodesic;
 /** @type {?} */
PolygonInput.prototype.paths;
 /** @type {?} */
PolygonInput.prototype.strokeColor;
 /** @type {?} */
PolygonInput.prototype.strokeOpacity;
 /** @type {?} */
PolygonInput.prototype.strokePosition;
 /** @type {?} */
PolygonInput.prototype.strokeWeight;
 /** @type {?} */
PolygonInput.prototype.visible;
 /** @type {?} */
PolygonInput.prototype.zIndex;
 /** @type {?} */
PolygonInput.prototype.options;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/polyline.ts:

/** @record @struct */
function PolylineOutput() {}
 /** @type {?} */
PolylineOutput.prototype.click;
 /** @type {?} */
PolylineOutput.prototype.dblclick;
 /** @type {?} */
PolylineOutput.prototype.drag;
 /** @type {?} */
PolylineOutput.prototype.dragend;
 /** @type {?} */
PolylineOutput.prototype.dragstart;
 /** @type {?} */
PolylineOutput.prototype.mousedown;
 /** @type {?} */
PolylineOutput.prototype.mousemove;
 /** @type {?} */
PolylineOutput.prototype.mouseout;
 /** @type {?} */
PolylineOutput.prototype.mouseover;
 /** @type {?} */
PolylineOutput.prototype.mouseup;
 /** @type {?} */
PolylineOutput.prototype.rightclick;

/** @record @struct */
function PolylineInput() {}
 /** @type {?} */
PolylineInput.prototype.clickable;
 /** @type {?} */
PolylineInput.prototype.draggable;
 /** @type {?} */
PolylineInput.prototype.editable;
 /** @type {?} */
PolylineInput.prototype.geodesic;
 /** @type {?} */
PolylineInput.prototype.icons;
 /** @type {?} */
PolylineInput.prototype.path;
 /** @type {?} */
PolylineInput.prototype.strokeColor;
 /** @type {?} */
PolylineInput.prototype.strokeOpacity;
 /** @type {?} */
PolylineInput.prototype.strokeWeight;
 /** @type {?} */
PolylineInput.prototype.visible;
 /** @type {?} */
PolylineInput.prototype.zIndex;
 /** @type {?} */
PolylineInput.prototype.options;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/street-view-panorama.ts:

/** @record @struct */
function StreetViewPanoramaOutput() {}
 /** @type {?} */
StreetViewPanoramaOutput.prototype.closeclick;
 /** @type {?} */
StreetViewPanoramaOutput.prototype.pano_changed;
 /** @type {?} */
StreetViewPanoramaOutput.prototype.position_changed;
 /** @type {?} */
StreetViewPanoramaOutput.prototype.pov_changed;
 /** @type {?} */
StreetViewPanoramaOutput.prototype.resize;
 /** @type {?} */
StreetViewPanoramaOutput.prototype.status_changed;
 /** @type {?} */
StreetViewPanoramaOutput.prototype.visible_changed;
 /** @type {?} */
StreetViewPanoramaOutput.prototype.zoom_changed;

/** @record @struct */
function StreetViewPanoramaInput() {}
 /** @type {?} */
StreetViewPanoramaInput.prototype.selector;
 /** @type {?} */
StreetViewPanoramaInput.prototype.options;
 /** @type {?} */
StreetViewPanoramaInput.prototype.addressControl;
 /** @type {?} */
StreetViewPanoramaInput.prototype.addressControlOptions;
 /** @type {?} */
StreetViewPanoramaInput.prototype.clickToGo;
 /** @type {?} */
StreetViewPanoramaInput.prototype.disableDefaultUI;
 /** @type {?} */
StreetViewPanoramaInput.prototype.disableDoubleClickZoom;
 /** @type {?} */
StreetViewPanoramaInput.prototype.enableCloseButton;
 /** @type {?} */
StreetViewPanoramaInput.prototype.fullscreenControl;
 /** @type {?} */
StreetViewPanoramaInput.prototype.fullscreenControlOptions;
 /** @type {?} */
StreetViewPanoramaInput.prototype.imageDateControl;
 /** @type {?} */
StreetViewPanoramaInput.prototype.linksControl;
 /** @type {?} */
StreetViewPanoramaInput.prototype.motionTracking;
 /** @type {?} */
StreetViewPanoramaInput.prototype.motionTrackingControl;
 /** @type {?} */
StreetViewPanoramaInput.prototype.panControl;
 /** @type {?} */
StreetViewPanoramaInput.prototype.panControlOptions;
 /** @type {?} */
StreetViewPanoramaInput.prototype.pano;
 /** @type {?} */
StreetViewPanoramaInput.prototype.position;
 /** @type {?} */
StreetViewPanoramaInput.prototype.pov;
 /** @type {?} */
StreetViewPanoramaInput.prototype.scrollwheel;
 /** @type {?} */
StreetViewPanoramaInput.prototype.showRoadLabels;
 /** @type {?} */
StreetViewPanoramaInput.prototype.visible;
 /** @type {?} */
StreetViewPanoramaInput.prototype.zoomControl;
 /** @type {?} */
StreetViewPanoramaInput.prototype.zoomControlOptions;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/traffic-layer.ts:

/** @record @struct */
function TrafficLayerOutput() {}

/** @record @struct */
function TrafficLayerInput() {}
 /** @type {?} */
TrafficLayerInput.prototype.autoRefresh;
 /** @type {?} */
TrafficLayerInput.prototype.options;
// externs from /home/abdellatif/www/contrib/ng2-map/.ng_build/ts/directives/transit-layer.ts:

/** @record @struct */
function TransitLayerOutput() {}

/** @record @struct */
function TransitLayerInput() {}
